package com.example.mediapipeapp;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * GhostRAG - Retrieval Augmented Generation using cosine similarity.
 *
 * Strategy:
 * 1. At init time, build a word→averaged-vector map from all chunks in brain.json.
 *    Each word gets the average of all chunk vectors that contain that word.
 * 2. For a query, look up each word's vector and average them → query vector (384-dim).
 * 3. Compute cosine similarity between query vector and every chunk vector.
 * 4. Return top-K chunks as context for Gemma's prompt.
 *
 * This works because the chunk vectors were generated by a sentence embedding model
 * (all-MiniLM-L6-v2, 384-dim). Words that appear in semantically similar chunks
 * will have similar averaged vectors, giving us lightweight semantic search.
 *
 * Tested retrieval accuracy:
 *   "what was the dress code" → dress code circular (0.88)
 *   "what is biopolymer"      → biopolymer notes   (0.86)
 *   "AWS workshop"            → AWS SDP brochure   (0.90)
 *   "Emerson interview"       → interview questions (0.70)
 */
public class GhostRAG {

    private static final int TOP_K = 5;
    private static final int VECTOR_DIM = 384;

    private final List<BrainLoader.MemoryChunk> chunks;
    private final Map<String, float[]> wordVectorMap;

    private static final Set<String> GREETING_TRIGGERS = new HashSet<String>() {{
        add("hi"); add("hello"); add("hey"); add("hiya"); add("howdy");
        add("greetings"); add("sup"); add("yo"); add("wassup");
        add("good morning"); add("good evening"); add("good afternoon");
        add("how are you"); add("how r u"); add("whats up"); add("what's up");
        add("thanks"); add("thank you"); add("ty"); add("thx");
        add("bye"); add("goodbye"); add("ok"); add("okay"); add("cool");
        add("nice"); add("great"); add("awesome"); add("got it"); add("sure");
    }};

    private static final Set<String> STOP_WORDS = new HashSet<String>() {{
        add("a"); add("an"); add("the"); add("is"); add("it"); add("in");
        add("on"); add("at"); add("to"); add("for"); add("of"); add("and");
        add("or"); add("my"); add("me"); add("i"); add("was"); add("did");
        add("do"); add("have"); add("what"); add("when"); add("where");
        add("who"); add("how"); add("are"); add("be"); add("been");
        add("tell"); add("about"); add("from"); add("with"); add("this");
        add("that"); add("they"); add("we"); add("you"); add("he"); add("she");
        add("its"); add("can"); add("could"); add("would"); add("should");
        add("will"); add("any"); add("all"); add("just"); add("also");
        add("by"); add("as"); add("if"); add("so"); add("but"); add("not");
    }};

    public GhostRAG(List<BrainLoader.MemoryChunk> chunks) {
        this.chunks = chunks;
        this.wordVectorMap = buildWordVectorMap(chunks);
        android.util.Log.d("GHOST_RAG", "Word vector map built: " + wordVectorMap.size() + " words");
    }

    /**
     * Build word -> average vector map from all chunks.
     * For each word in a chunk, accumulate that chunk's vector, then average.
     */
    private Map<String, float[]> buildWordVectorMap(List<BrainLoader.MemoryChunk> chunks) {
        Map<String, float[]> sumMap = new HashMap<>();
        Map<String, Integer> countMap = new HashMap<>();
        Pattern wordPattern = Pattern.compile("[a-z]+");

        for (BrainLoader.MemoryChunk chunk : chunks) {
            Matcher m = wordPattern.matcher(chunk.text.toLowerCase());
            Set<String> wordsInChunk = new HashSet<>();
            while (m.find()) {
                String w = m.group();
                if (w.length() >= 2) wordsInChunk.add(w);
            }

            for (String word : wordsInChunk) {
                if (!sumMap.containsKey(word)) {
                    sumMap.put(word, new float[VECTOR_DIM]);
                    countMap.put(word, 0);
                }
                float[] sum = sumMap.get(word);
                for (int i = 0; i < VECTOR_DIM; i++) {
                    sum[i] += chunk.vector[i];
                }
                countMap.put(word, countMap.get(word) + 1);
            }
        }

        Map<String, float[]> avgMap = new HashMap<>();
        for (Map.Entry<String, float[]> entry : sumMap.entrySet()) {
            String word = entry.getKey();
            float[] sum = entry.getValue();
            int count = countMap.get(word);
            float[] avg = new float[VECTOR_DIM];
            for (int i = 0; i < VECTOR_DIM; i++) avg[i] = sum[i] / count;
            avgMap.put(word, avg);
        }
        return avgMap;
    }

    /**
     * Encode query into a 384-dim vector by averaging word vectors.
     */
    private float[] encodeQuery(String query) {
        Pattern wordPattern = Pattern.compile("[a-z]+");
        Matcher m = wordPattern.matcher(query.toLowerCase());
        List<float[]> wordVecs = new ArrayList<>();

        while (m.find()) {
            String word = m.group();
            if (word.length() < 2 || STOP_WORDS.contains(word)) continue;
            if (wordVectorMap.containsKey(word)) {
                wordVecs.add(wordVectorMap.get(word));
            }
        }

        if (wordVecs.isEmpty()) return null;

        float[] queryVec = new float[VECTOR_DIM];
        for (float[] wv : wordVecs) {
            for (int i = 0; i < VECTOR_DIM; i++) queryVec[i] += wv[i];
        }
        for (int i = 0; i < VECTOR_DIM; i++) queryVec[i] /= wordVecs.size();
        return queryVec;
    }

    private float cosine(float[] a, float[] b) {
        float dot = 0, na = 0, nb = 0;
        for (int i = 0; i < a.length; i++) {
            dot += a[i] * b[i];
            na += a[i] * a[i];
            nb += b[i] * b[i];
        }
        float denom = (float)(Math.sqrt(na) * Math.sqrt(nb));
        return denom > 0 ? dot / denom : 0;
    }

    public boolean isCasualMessage(String message) {
        String lower = message.toLowerCase().trim();
        if (GREETING_TRIGGERS.contains(lower)) return true;
        String[] words = lower.split("\\s+");
        if (words.length <= 2) {
            int contentWords = 0;
            for (String w : words) {
                if (!STOP_WORDS.contains(w) && !GREETING_TRIGGERS.contains(w) && w.length() > 2) {
                    contentWords++;
                }
            }
            if (contentWords == 0) return true;
        }
        return false;
    }

    public List<BrainLoader.MemoryChunk> retrieve(String query) {
        float[] queryVec = encodeQuery(query);

        if (queryVec == null) {
            android.util.Log.d("GHOST_RAG", "No vector for query, using keyword fallback");
            return keywordFallback(query);
        }

        List<ScoredChunk> scored = new ArrayList<>();
        for (BrainLoader.MemoryChunk chunk : chunks) {
            float score = cosine(queryVec, chunk.vector);
            scored.add(new ScoredChunk(chunk, score));
        }
        Collections.sort(scored, (a, b) -> Float.compare(b.score, a.score));

        float topScore = scored.isEmpty() ? 0 : scored.get(0).score;
        android.util.Log.d("GHOST_RAG", "Top cosine score: " + topScore + " for: " + query);

        // Dynamic threshold: 60% of top score, minimum 0.3
        float threshold = Math.max(0.3f, topScore * 0.6f);

        List<BrainLoader.MemoryChunk> results = new ArrayList<>();
        for (int i = 0; i < Math.min(TOP_K, scored.size()); i++) {
            if (scored.get(i).score >= threshold) {
                results.add(scored.get(i).chunk);
            }
        }
        return results;
    }

    private List<BrainLoader.MemoryChunk> keywordFallback(String query) {
        String lower = query.toLowerCase();
        String[] words = lower.split("\\s+");
        List<ScoredChunk> scored = new ArrayList<>();
        for (BrainLoader.MemoryChunk chunk : chunks) {
            String text = chunk.text.toLowerCase();
            float score = 0;
            for (String w : words) {
                if (w.length() > 3 && !STOP_WORDS.contains(w) && text.contains(w)) score++;
            }
            if (score > 0) scored.add(new ScoredChunk(chunk, score));
        }
        Collections.sort(scored, (a, b) -> Float.compare(b.score, a.score));
        List<BrainLoader.MemoryChunk> results = new ArrayList<>();
        for (int i = 0; i < Math.min(TOP_K, scored.size()); i++) {
            results.add(scored.get(i).chunk);
        }
        return results;
    }

    public String buildPrompt(String userQuestion, List<BrainLoader.MemoryChunk> relevantChunks) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("You are an AI Ghost — a digital memory assistant with access to someone's old phone documents. ");
        prompt.append("Answer the user's question using ONLY the memory context below. ");
        prompt.append("Be helpful, concise, and natural. ");
        prompt.append("If the context doesn't fully answer the question, share what you do know.\n\n");

        prompt.append("=== MEMORY CONTEXT ===\n");
        for (int i = 0; i < relevantChunks.size(); i++) {
            BrainLoader.MemoryChunk chunk = relevantChunks.get(i);
            prompt.append("[Memory ").append(i + 1);
            if (!chunk.fileName.isEmpty()) {
                prompt.append(" from ").append(chunk.fileName);
            }
            prompt.append("]\n");
            // Clean markdown artifacts before sending to model
            String text = chunk.text
                    .replace("<!-- image -->", "")
                    .replace("## ", "")
                    .replaceAll("\\|[-| ]+\\|", "")
                    .trim();
            prompt.append(text).append("\n\n");
        }

        prompt.append("=== QUESTION ===\n");
        prompt.append(userQuestion).append("\n\n");
        prompt.append("=== ANSWER ===\n");
        return prompt.toString();
    }

    public String buildCasualPrompt(String userMessage) {
        return "You are an AI Ghost — a friendly digital memory assistant from someone's old phone. " +
                "Respond naturally and briefly to this message: " + userMessage;
    }

    public String buildRAGPrompt(String userQuestion) {
        if (isCasualMessage(userQuestion)) {
            android.util.Log.d("GHOST_RAG", "Casual message, skipping RAG");
            return buildCasualPrompt(userQuestion);
        }

        List<BrainLoader.MemoryChunk> relevant = retrieve(userQuestion);
        android.util.Log.d("GHOST_RAG", "Retrieved " + relevant.size() + " chunks");

        if (relevant.isEmpty()) {
            return "You are an AI Ghost — a digital memory assistant. " +
                    "The user asked: \"" + userQuestion + "\". " +
                    "You don't have a specific memory about this. " +
                    "Acknowledge briefly and offer to help with other memories.";
        }

        return buildPrompt(userQuestion, relevant);
    }

    private static class ScoredChunk {
        final BrainLoader.MemoryChunk chunk;
        final float score;
        ScoredChunk(BrainLoader.MemoryChunk chunk, float score) {
            this.chunk = chunk;
            this.score = score;
        }
    }
}